WALL_DIR=/home/yohei/wallpapers
RECURSIVE=1
BACKEND=swww
DISPLAY_TARGET=All\ displays
SWWW_RESIZE=crop
SWWW_TRANSITION_TYPE=grow
SWWW_TRANSITION_DURATION=0.8
SWWW_TRANSITION_FPS=30
SWWW_FILTER=Lanczos3
HYPERPAPER_MODE=cover
FILTER_KIND=ALL
LAST_SEL=0
LAST_FOCUS=/home/yohei/wallpapers/camel.jpg
LAST_APPLIED=''
