general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# TTE screensaver after 5 minutes
listener {
    timeout = 300
    on-timeout = kitty --title tte-screensaver -e ~/dotfiles/scripts/tte-screensaver.sh
    on-resume = pkill -f tte-screensaver
}
