# Popping and Locking theme for btop
# Based on the kitty Popping and Locking color scheme (Gruvbox-derived)

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#181921"

# Main text color
theme[main_fg]="#a89984"

# Title color for boxes
theme[title]="#ebdbb2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#fabd2f"

# Background color of selected items
theme[selected_bg]="#1d2021"

# Foreground color of selected items
theme[selected_fg]="#f42c3e"

# Color of inactive/disabled text
theme[inactive_fg]="#928374"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#928374"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b8bb26"

# Cpu box outline color
theme[cpu_box]="#458588"

# Memory/disks box outline color
theme[mem_box]="#689d6a"

# Net up/down box outline color
theme[net_box]="#b16286"

# Processes box outline color
theme[proc_box]="#d79921"

# Box divider line and small boxes line color
theme[div_line]="#928374"

# Temperature graph colors
theme[temp_start]="#458588"
theme[temp_mid]="#d3869b"
theme[temp_end]="#f42c3e"

# CPU graph colors
theme[cpu_start]="#b8bb26"
theme[cpu_mid]="#fabd2f"
theme[cpu_end]="#f42c3e"

# Mem/Disk free meter
theme[free_start]="#458588"
theme[free_mid]=""
theme[free_end]="#99c6ca"

# Mem/Disk cached meter
theme[cached_start]="#689d6a"
theme[cached_mid]=""
theme[cached_end]="#7ec16e"

# Mem/Disk available meter
theme[available_start]="#d79921"
theme[available_mid]=""
theme[available_end]="#fabd2f"

# Mem/Disk used meter
theme[used_start]="#cc241d"
theme[used_mid]=""
theme[used_end]="#f42c3e"

# Download graph colors
theme[download_start]="#458588"
theme[download_mid]="#99c6ca"
theme[download_end]="#ebdbb2"

# Upload graph colors
theme[upload_start]="#b16286"
theme[upload_mid]="#d3869b"
theme[upload_end]="#ebdbb2"
